marmelab/atomic-crm

scripts/ghpages-deploy.mjs

The static pages were not deployed automatically as git user was not defined
Force a user in gh pages script

Fix(ops): GitHub pages were not pushed as expected

---

supabase/migrations/20240730075029_init_db.sql
supabase/migrations/20240730075425_init_triggers.sql

Views are public by default and could leak data
Add security to views except `init_state` as it MUST be public and is designed to be secure
You must reset DB, add contacts and access to `http://127.0.0.1:54321/rest/v1/contacts_summary`. You should get and empty array

Fix(views): Add security invokers to views to avoid data leak

---

supabase/migrations/20240807082449_remove-aquisition.sql

contacts_summary view was dropped in a migration
recreate contacts_summary view in the remove acquisition migration

Fix(migrations): recreate contact_summary view in remove acquisition migration

---

.github/pull_request_template.md
.github/workflows/check.yml
README.md
doc/data-providers.md
makefile
package-lock.json
package.json
setupFiles/jest.ts
src/providers/fakerest/authProvider.ts
src/providers/fakerest/dataProvider.ts
src/providers/fakerest/index.ts
src/providers/fakerest/internal/transformContainsFilter.spec.ts
src/providers/fakerest/internal/transformContainsFilter.ts
src/providers/fakerest/internal/transformFilter.ts
src/providers/fakerest/internal/transformInFilter.spec.ts
src/providers/fakerest/internal/transformInFilter.ts
src/providers/fakerest/internal/transformOrFilter.spec.ts
src/providers/fakerest/internal/transformOrFilter.ts
src/providers/fakerest/supabaseAdapter.spec.ts
src/providers/fakerest/supabaseAdapter.ts
tsconfig.json
vitest.config.ts

We want to support both supabase and fake rest as auth and data providers. However, supabase list filters are not compatible with fake rest's ones.
Filters to support:
Add an adapter from supabase filters to fake rest filters.
Replace `dataProvider` and `authProvider` by fake rest one's in `root/CRM.tsx`

Feat(dataProvider): Add supabase to fakerest filter adapter

---

package-lock.json

Dependency install fails on macOS
Update package-lock.json to include rollup binaries
Clean install on macOS

Fix(macOS): Update package lock to include rollup native binaries

---

.github/workflows/deploy.yml
README.md
doc/github-actions.md
scripts/ghpages-deploy.mjs

We want to deploy Atomic CRM static site to another repository
Add a support for a GitHub action secret to configure the target repository.

Feat(ops): Add option to deploy to another repository

---

src/providers/supabase/authProvider.ts
src/providers/supabase/dataProvider.ts

Initial load time is too long if app is not initialized
Avoid `ra-supabase` permission check if app is not initialized
Reset you DB and create a new account

Fix(ux): Reduce initial loading time

---

src/Header.tsx
src/login/SignupPage.tsx
src/providers/supabase/authProvider.ts
src/root/CRM.tsx
src/sales/SalesCreate.tsx
src/sales/SalesEdit.tsx
src/sales/SalesList.tsx

- First user cannot create sale on first login
- Login page is slow to load
- Move permission check to slaes pages
- Refetch permissions on signup
Cleanup your db while your are still connected and create a new account

Fix(perf): Logout user if db has been reset and improve login page load performance

---

supabase/migrations/20240808141826_init_state_configure.sql

Init state view was leaking sales count
Use subquery to avoid data leak
Create multiple sales and access to `init_state`

Sec(init_state): init_state view is no longer leaking sales count

---

src/login/SignupPage.tsx

On the signup page, the logo is almost invisible (white on a white background).
Invert the logo color on the signup page
Clear your database and run `make start`

fix(crm): Fix signup page logo color

---

README.md
package-lock.json
package.json
public/auth-callback.html
src/providers/fakerest/dataProvider.ts
src/providers/supabase/authProvider.ts
src/sales/SalesCreate.tsx
src/sales/SalesInputs.tsx
supabase/config.toml
supabase/functions/users/index.ts
supabase/templates/invite.html
supabase/templates/recovery.html

As a new user, I want to know when I'm invited to join the CRM and configure my own password
Implement setPassword and Invite user via Supabase. Handle in HashRouter
1. Launch demo
2. From Login page go to ResetPasswordPage. 
3. Send recovery email and go to http://localhost:54324/
4. Click on link and reset password
1. Go on Sales Create
2. Create a new sales and go to http://localhost:54324/
3. Click on mail and set password

Feat(auth): Handle resetPassword and Invite user

---

src/contacts/useContactImport.tsx
src/providers/fakerest/internal/listParser.ts
src/providers/fakerest/internal/transformContainsFilter.spec.ts
src/providers/fakerest/internal/transformContainsFilter.ts
src/providers/fakerest/internal/transformInFilter.spec.ts
src/providers/fakerest/internal/transformInFilter.ts

During imports, companies and tags are duplicated
Use an '@in' operator instead of an array in `useContactImport`
1. Go to the contacts page
2. Click on the import button
3. Download the sample CSV
4. Upload the sample CSV
5. Import

Fix(import): tags and companies are no loger duplicated during imports

---

package-lock.json
src/tests/supabase/functions/postmark.spec.ts
supabase/functions/postmark/extractMailContactData.ts

When sending an email to an address that has no first and last name, it creates a contact with no first and last name.
We should use the part of the email before the @ and split it between dots to fill the first and last name.
Send a message to an email not in your contacts.
Alternatively, this can be tested locally using the sample `curl` command [here](https://github.com/marmelab/atomic-crm/blob/1ddf5389db4c5c76d778a1cf8f9d3c3e58d50564/supabase/functions/postmark/index.ts#L118-L206) and clearing the `To.Name` field.

fix(mail): Support recipient with empty Name

---

src/providers/supabase/authProvider.ts

After sign up, the user is not automatically logged in.
the user has to log in after sign up for the first user
the same happens after I reset my password: I am not automatically logged in.
Apply the same `checkAuth` implementation as in [`ra-supabase`](https://github.com/marmelab/ra-supabase/pull/67/files#diff-2f66cc28128c0000e6210759afdbf8eb6cb7597375968d7ab4e3709e2c34cad1), and also extend the mechanism to the signup page.
1st issue: reset the db, create the 1st user, make sure you are automatically signed in.
2nd issue: use the forgot-password feature to reset your password. After choosing a new password, make sure you are automatically signed in.

fix(login): Fix user is not automatically logged in after signup

---

src/notes/Note.tsx

There is too much spacing when rendering notes
Reduce spacing
[Capture vidéo du 09-08-2024 14:46:12.webm](https://github.com/user-attachments/assets/338299c6-beda-4675-b631-3b1dd1660151)

Fix(note): Improve note spacing

---

src/tasks/AddTask.tsx

Contact last activity is not updated when a task has been added
Add an onSucces hook that updates the contact last activity when creating a task
Add a task to a contact

Feat(tasks): Update contact last seen when creating a task

---

.github/workflows/deploy.yml

Make atomic-crm GitHub workflow pass on forks
The deploy job now checks for the secrets presence before launching the supabase setup.
It also list all missing secrets as warning in the job summary
Out of scope: Display an error message in the app when supabase is not properly configured.
- Fork the atomic-crm repository, including the branches.
- Activate github page on the gh-pages branch in settings ([see docs](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-from-a-branch))
- Merge this branch fork on your fork master
- Check the deploy job result
- Check that the gh-page branch has been updated
- Go to the gh page url to check the page has been deployed …

skip gh action task when needed secrets are missing

---

.gitignore
index.html
makefile
package-lock.json
package.json
src/index.tsx
src/script.tsx
vite.lib.config.ts

We cannot install atomic-crm from npm
Add a lib build along the current app build with:
- esm 
- cjs
- types
To test without actually publishing the module:
- run npm pack to create an archive
- create a npm project, aor use an existing one
- add `"atomic-crm": "file://path-to-the-archive/atomic-crm-0.0.1.tgc"`
- run npm install
- start to play with the atomic-crm library
- Admire the type
- switch your project type between module and commonjs to use both version.
Note: only the CRM component is exposed for now

Add a build-lib command to be able to publish an atomic-crm node module

---

package-lock.json
package.json
scripts/supabase-remote-init.mjs

Fixes #75
As expected, the previous version of the script wasn't reliable as it used the human readable output of the Supabase CLI.
Use the new `output` CLI argument allowing us to get a JSON output.
Run the `make supabase-remote-init`

Refactor Remote Init Script

---

doc/developer/deploy.md
doc/developer/supabase-configuration.md

After deploying the supabase instance, it's unclear whether one should invite initial users through the supabase dashboard
Improve the deploy documentation to explain how to do the initial setup

Improve documentation about initial production setup

---

doc/user/inbound-email.md

Looks like the file structure changed - so updating this reference.
URL reference is broken
Fixes the url reference
Navigate to the inbound-email.md
Click on the Inbound Email Setup Link
Also, please make sure to read the [contributing guidelines](https://github.com/marmelab/atomic-crm#contributing).

Update url for inbound-email-configuration

---

src/tasks/AddTask.tsx

Closes #84
New Task dialog closes even if task is invalid
The dialog is closed on click on the save button. It should only be closed when the mutation is successful.

Fix New Task dialog closes even if task is invalid

---

vite.config.ts

Debugging in production is hard with transpiled sources
Enable TS sourcemap in production as explained at https://marmelab.com/react-admin/Vite.html#sourcemaps-in-production
- `make build`
- `npm run preview`
- check that all react-admin related packages load their files from their `src` directory

Allow TS sourcemaps in production

---

src/atomic-crm/contacts/ContactListFilter.tsx
src/components/admin/search-input.tsx
src/components/admin/text-input.tsx

Closes https://github.com/marmelab/atomic-crm/issues/106
I found that the placeholder text overlaps with the search icon in the contact input field.
Additionally, the contact sidebar icons are inconsistent in their width and height.
- Search Input
- Icon Contact Filter
* Changed `w-fit` to `w-full` in the `search-input` component to prevent the placeholder from overlapping with the search icon.
* Removed fixed `width` and `height` attributes on the sidebar contact icons to ensure consistent sizing with the existing icons.
1. Navigate to the **Contacts** section.
2. Verify that the search input placeholder no longer overlaps with the search icon.
3. Check the contact sidebar icons to confirm that their width and height are now consistent with each other.
Also, please make sure to read the …

[CHORE] - adjust UI contact component search input, icon contact filter
